# Generated by Django 3.1.7 on 2021-03-26 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('question_text', models.TextField()),
                ('co2_formula', models.CharField(max_length=512, null=True)),
                ('water_formula', models.CharField(max_length=512, null=True)),
                ('waste_formula', models.CharField(max_length=512, null=True)),
                ('version', models.CharField(max_length=128)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('action', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledges.action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'action')},
            },
        ),
        migrations.CreateModel(
            name='FoodPledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=128)),
                ('current_meals', models.IntegerField()),
                ('vegetarian_meals', models.DecimalField(choices=[(2.5, '0'), (2.5, '1'), (2.5, '2'), (2.5, '3'), (2.5, '4'), (2.5, '5'), (3.0, '6')], decimal_places=2, max_digits=3)),
                ('pledge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledges.pledge')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyPledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=128)),
                ('energy_supplier', models.DecimalField(choices=[(0.5, 'bog_standard'), (0.0, 'green_supplier')], decimal_places=2, max_digits=3)),
                ('number_of_people', models.IntegerField()),
                ('heating_source', models.DecimalField(choices=[(5.0, 'gas or oil'), (3.0, 'electricity')], decimal_places=2, max_digits=3)),
                ('pledge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledges.pledge')),
            ],
        ),
    ]
